# Generated by Django 3.1.5 on 2021-01-17 12:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210116_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='logo.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
