# Generated by Django 3.1.5 on 2021-01-23 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userpostrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(related_name='posts', through='user.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
